### PR TITLE
Check for optional value during template argument rewriting

### LINKED ISSUE #339: dredd throws 'std::bad_optional_access' when handling template expression rewriting
Applying dredd to
```
template <long> struct b;
template <long c> b<c> d;

void foo() {
  int x = 2;
}
```
results in 
```
terminate called after throwing an instance of 'std::bad_optional_access'
  what():  bad optional access
 #0 0x000055e3b9b395d8 llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) (dredd/third_party/clang+llvm/bin/dredd+0x24235d8)
 #1 0x000055e3b9b3755c llvm::sys::RunSignalHandlers() (dredd/third_party/clang+llvm/bin/dredd+0x242155c)
 #2 0x000055e3b9b39d78 SignalHandler(int) Signals.cpp:0:0
 #3 0x00007efef47cc520 (/lib/x86_64-linux-gnu/libc.so.6+0x42520)
 #4 0x00007efef48209fc pthread_kill (/lib/x86_64-linux-gnu/libc.so.6+0x969fc)
 #5 0x00007efef47cc476 gsignal (/lib/x86_64-linux-gnu/libc.so.6+0x42476)
 #6 0x00007efef47b27f3 abort (/lib/x86_64-linux-gnu/libc.so.6+0x287f3)
 #7 0x00007efef4a77b9e (/lib/x86_64-linux-gnu/libstdc++.so.6+0xa2b9e)
 #8 0x00007efef4a8320c (/lib/x86_64-linux-gnu/libstdc++.so.6+0xae20c)
 #9 0x00007efef4a83277 (/lib/x86_64-linux-gnu/libstdc++.so.6+0xae277)
#10 0x00007efef4a834d8 (/lib/x86_64-linux-gnu/libstdc++.so.6+0xae4d8)
#11 0x000055e3b7b4dee5 (dredd/third_party/clang+llvm/bin/dredd+0x437ee5)
#12 0x000055e3b7b6eb2a (dredd/third_party/clang+llvm/bin/dredd+0x458b2a)
#13 0x000055e3b7b6c19e dredd::MutateAstConsumer::HandleTranslationUnit(clang::ASTContext&) /home/jjf120/dredd/src/libdredd/src/mutate_ast_consumer.cc:167:14
#14 0x000055e3b81e7216 clang::ParseAST(clang::Sema&, bool, bool) (dredd/third_party/clang+llvm/bin/dredd+0xad1216)
#15 0x000055e3b7f6bcf7 clang::FrontendAction::Execute() (dredd/third_party/clang+llvm/bin/dredd+0x855cf7)
#16 0x000055e3b7ede624 clang::CompilerInstance::ExecuteAction(clang::FrontendAction&) (dredd/third_party/clang+llvm/bin/dredd+0x7c8624)
#17 0x000055e3b7ead100 clang::tooling::FrontendActionFactory::runInvocation(std::shared_ptr<clang::CompilerInvocation>, clang::FileManager*, std::shared_ptr<clang::PCHContainerOperations>, clang::DiagnosticConsumer*) (dredd/third_party/clang+llvm/bin/dredd+0x797100)
#18 0x000055e3b7eacea0 clang::tooling::ToolInvocation::runInvocation(char const*, clang::driver::Compilation*, std::shared_ptr<clang::CompilerInvocation>, std::shared_ptr<clang::PCHContainerOperations>) (dredd/third_party/clang+llvm/bin/dredd+0x796ea0)
#19 0x000055e3b7eab783 clang::tooling::ToolInvocation::run() (dredd/third_party/clang+llvm/bin/dredd+0x795783)
#20 0x000055e3b7eae7ef clang::tooling::ClangTool::run(clang::tooling::ToolAction*) (dredd/third_party/clang+llvm/bin/dredd+0x7987ef)
#21 0x000055e3b7b4bc07 main /home/jjf120/dredd/src/dredd/src/main.cc:124:32
#22 0x00007efef47b3d90 (/lib/x86_64-linux-gnu/libc.so.6+0x29d90)
#23 0x00007efef47b3e40 __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x29e40)
#24 0x000055e3b7b4b6f5 _start (dredd/third_party/clang+llvm/bin/dredd+0x4356f5)
Aborted
```

### PR DESCRIPTION
**Pull request by JonathanFoo0523**
Fix an issue where Dredd throws `bad_optional_access` when trying to
rewrite a template argument that can't be evaluated as an integer.

Fixes #339

### CODE REVIEW

File: src/libdredd/src/mutate_ast_consumer.cc [hunk 1]
```diff
@@ -108,37 +108,7 @@ void MutateAstConsumer::HandleTranslationUnit(clang::ASTContext& ast_context) {
...
-          llvm::dyn_cast<clang::ConstantArrayType>(
-              constant_array_typeloc.getType()
-                  ->getAsArrayTypeUnsafe()
-                  ->getAsArrayTypeUnsafe())
-              ->getSize()
-              .getLimitedValue());
-      typeloc = constant_array_typeloc.getElementLoc();
-    }
-  }
+  RewriteExpressionInMainFile();
```
Comment (afd) [inline src/libdredd/src/mutate_ast_consumer.cc:111]: I suggest using a plural - "RewriteExpressionsInMainFile" since it may be more than one expression.

**Review by afd — APPROVED** [review]
LGTM with one minor change.
